### ISSUE TITLE
适配6.5.0问题

### ISSUE THREAD

**Issue by MeiJiaYun** [tianjing/tgtools-flowable#1]
大佬你好，我拉取源码，并修改flowable版本为6.5.0，发现代码还需更改，麻烦大佬适配6.5.0

**Comment by tianjing** [comment]
你可以按那思路 改改
时间是个问题T_T

田径


-------- 原始邮件 --------
发件人： Jiayun <notifications@github.com>
日期： 2020年8月11日周二 18:49
收件人： tianjing/tgtools-flowable <tgtools-flowable@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主 题： [tianjing/tgtools-flowable] 适配6.5.0问题 (#1)

大佬你好，我拉取源码，并修改flowable版本为6.5.0，发现代码还需更改，麻烦大佬适配6.5.0

―

**Comment by MeiJiaYun** [comment]
大佬厉害，已修复支持6.5.0
